name: Linting
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: python:3.8.15-slim
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - run: pip install pre-commit
      - run: pip install -r requirements.txt
      - run: pre-commit run --all-files
